name: Deploy to S3

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # جلب الكود
    - name: Checkout code
      uses: actions/checkout@v4
      
    # إعداد AWS CLI
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    # نشر إلى S3
    - name: Deploy to S3
      run: |
        aws s3 sync static-website/ s3://${{ secrets.S3_BUCKET_NAME }} --delete
